apiVersion: v1
kind: Pod
metadata:
 name: myapp-pod
 labels:
  app: myapp
  type: front-end
spec:
 containers:
 - name: terraform
   image: docker.io/alivelusai/terrakubectl
   command: [ "/bin/sh" , "-c", "tail -f /dev/null" ]