# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2023-05-07T09:01:03Z","labels":{"app":"nginx"},"name":"my-nginx-svc","namespace":"default","resourceVersion":"3489","uid":"38c9e9a9-fe8d-4764-bc36-b61d8e8a0b90"},"spec":{"clusterIP":"10.97.75.236","clusterIPs":["10.97.75.236"],"externalTrafficPolicy":"Cluster","internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"nodePort":30036,"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"nginx"},"sessionAffinity":"None","type":"NodePort"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2023-05-07T09:01:03Z"
  labels:
    app: nginx
  name: my-nginx-svc
  namespace: default
  resourceVersion: "3694"
  uid: 38c9e9a9-fe8d-4764-bc36-b61d8e8a0b90
spec:
  clusterIP: 10.97.75.236
  clusterIPs:
  - 10.97.75.236
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30036
    port: 80
    protocol: TCP
    targetPort: 9090
  selector:
    app: nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
